spring.datasource.url=jdbc:mysql://db4free.net:3306/wwk_test?useSSL=false&serverTimezone=Asia/Shanghai
spring.datasource.username=xilemengi
spring.datasource.password=12345678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
